### ISSUE TITLE
Only loads spec files with .js extension

### ISSUE THREAD

**Issue by diegocouto** [searls/jasmine-rails#178]
I'm using jasmine-rails 0.12.2v with Sprockets and local Phantomjs. This is my jasmine.yml (I'm relying on assets pipeline):

```yml
# minimalist jasmine.yml configuration when leveraging asset pipeline
spec_files:
  - "**/*[Ss]pec.{js.jsx, js, jsx}"

use_phantom_gem: false
```

I've create a sample file (**sample_spec.js.jsx**) and when I try to run **rake spec:javascripts** it always throw:

    ActionView::Template::Error: couldn't find file 'sample_spec.js.jsx' with type 'application/javascript'

On my environment, test will only run when using a .js extension for spec files.
