### ISSUE TITLE
browser not loading specs / assets

### ISSUE THREAD

**Issue by gerad** [searls/jasmine-rails#8]
See also https://github.com/searls/jasmine-rails/issues/4#issuecomment-6133596

I'm running rails-3.2.6 and trying to use jasmine rails to run specs in the browser, but none of the javascript assets (specs or actual source code) are being loaded by the in browser spec_runner.

everything works fine from the command line

here's my `jasmine.yml`

``` yml
# src_files
#
# Return an array of filepaths relative to src_dir to include before jasmine specs.
# Default: []
#
# EXAMPLE:
#
# src_files:
#   - lib/source1.js
#   - lib/source2.js
#   - dist/**/*.js
#
src_files:
  - "vendor/assets/**/*.{js,coffee}"
  - "lib/assets/**/*.{js,coffee}"
  - "app/assets/**/*.{js,js.coffee}"

# stylesheets
#
# Return an array of stylesheet filepaths relative to src_dir to include before jasmine specs.
# Default: []
#
# EXAMPLE:
#
# stylesheets:
#   - css/style.css
#   - stylesheets/*.css
#
stylesheets:
  - "vendor/assets/**/*.{css,styl}"
  - "lib/assets/**/*.{css,styl}"
  - "app/assets/**/*.{css,styl}"

# helpers
#
# Return an array of filepaths relative to spec_dir to include before jasmine specs.
# Default: ["helpers/**/*.js"]
#
# EXAMPLE:
#
# helpers:
#   - helpers/**/*.js
#
helpers:
  - "helpers/**/*.{js,coffee}"

# spec_files
#
# Return an array of filepaths relative to spec_dir to include.
# Default: ["**/*[sS]pec.js"]
#
# EXAMPLE:
#
# spec_files:
#   - **/*[sS]pec.js
#
spec_files:
  - "./**/*[sS]pec.{js,js.coffee}"

# src_dir
#
# Source directory path. Your src_files must be returned relative to this path. Will use root if left blank.
# Default: project root
#
# EXAMPLE:
#
# src_dir: public
#
src_dir:

# spec_dir
#
# Spec directory path. Your spec_files must be returned relative to this path.
# Default: spec/javascripts
#
# EXAMPLE:
#
# spec_dir: spec/javascripts
#
spec_dir: spec/javascripts

```

I'll keep digging and submit a fix if I can...
